### ISSUE TITLE
Error "too many values to unpack" after running xoauth.py

### ISSUE THREAD

**Issue by qupro** [mglukhovsky/drafter#2]
After running `python xoauth.py --generate_oauth_token --user=xxxx@gmail.com` with my corresponding gmail account I get this error:

```
Traceback (most recent call last):
  File "xoauth.py", line 482, in <module>
    main(sys.argv)
  File "xoauth.py", line 472, in main
    google_accounts_url_generator)
  File "xoauth.py", line 278, in GenerateRequestToken
    response_params = ParseUrlParamString(response)
  File "xoauth.py", line 213, in ParseUrlParamString
    k, v = kv.split('=')
ValueError: too many values to unpack
```

**Comment by mglukhovsky** [comment]
Google may have deprecated this authentication method. I'll take a look this weekend to see what I can do. 👍
